#ifndef FSAIRSOUNDENUM_IS_INCLUDED
#define FSAIRSOUNDENUM_IS_INCLUDED
/* { */

/* Memo to myself.
  1. Do not change the order.  It is used from DLLs.
  2. Do not put any C++ feature.  It is used from an Objective-C code. */


#ifndef YSRESULT_IS_DEFINED
#define YSRESULT_IS_DEFINED
typedef enum
{
	YSERR,
	YSOK
} YSRESULT;

#endif

#ifndef YSBOOL_IS_DEFINED
#define YSBOOL_IS_DEFINED
typedef enum
{
	YSFALSE,
	YSTRUE,
	YSTFUNKNOWN
} YSBOOL;
#endif


typedef enum
{
	FSSND_ENGINE_SILENT,
	FSSND_ENGINE_JETNORMAL,
	FSSND_ENGINE_JETAFTERBURNER,
	FSSND_ENGINE_PROPELLER,
	FSSND_ENGINE_TURBOPROP,
	FSSND_ENGINE_HELICOPTER,
	FSSND_ENGINE_CAR,
	FSSND_ENGINE_SHIP,
	// << 2010/04/21


	FSSND_NUM_ENGINETYPE
} FSSND_ENGINETYPE;

typedef enum
{
	FSSND_MACHINEGUN_SILENT,
	FSSND_MACHINEGUN_MACHINEGUN,
	// << 2010/04/21


	FSSND_NUM_MACHINEGUNTYPE,
} FSSND_MACHINEGUNTYPE;

typedef enum
{
	FSSND_ALARM_SILENT,
	FSSND_ALARM_STALL,
	FSSND_ALARM_MISSILE,
	FSSND_ALARM_TERRAIN,
	// << 2010/04/21


	FSSND_NUM_ALARMTYPE
} FSSND_ALARMTYPE;

typedef enum
{
	FSSND_ONETIME_SILENT,
	FSSND_ONETIME_DAMAGE,
	FSSND_ONETIME_MISSILE,
	FSSND_ONETIME_BANG,
	FSSND_ONETIME_BLAST,
	FSSND_ONETIME_TOUCHDWN,
	FSSND_ONETIME_HIT,
	FSSND_ONETIME_BLAST2,
	FSSND_ONETIME_GEARUP,
	FSSND_ONETIME_GEARDOWN,
	FSSND_ONETIME_BOMBSAWAY,
	FSSND_ONETIME_ROCKET,
	// << 2010/04/21

	FSSND_ONETIME_FLAPUP,
	FSSND_ONETIME_FLAPDOWN,
	// << 2010/06/06

	FSSND_ONETIME_NOTICE,
	// << 2012/02/01

	FSSND_NUM_ONETIMETYPE
} FSSND_ONETIMETYPE;

/* } */
#endif
